/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as _adminAnalyticsRouteImport } from './routes/__admin.analytics'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { ServerRoute as CustomScriptDotjsServerRouteImport } from './routes/customScript[.]js'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api/users'
import { ServerRoute as ApiUsersUserIdServerRouteImport } from './routes/api/users.$userId'
import { ServerRoute as ApiTmdbSearchServerRouteImport } from './routes/api/tmdb/search'
import { ServerRoute as ApiTmdbMultiSearchServerRouteImport } from './routes/api/tmdb/multi-search'
import { ServerRoute as ApiAnalyticsVisitServerRouteImport } from './routes/api/analytics/visit'
import { ServerRoute as ApiAnalyticsSummaryServerRouteImport } from './routes/api/analytics/summary'
import { ServerRoute as ApiTmdbPeopleSearchServerRouteImport } from './routes/api/tmdb/people.search'
import { ServerRoute as ApiTmdbMoviesUpcomingServerRouteImport } from './routes/api/tmdb/movies.upcoming'
import { ServerRoute as ApiTmdbMoviesTrendingServerRouteImport } from './routes/api/tmdb/movies.trending'
import { ServerRoute as ApiTmdbMoviesTopRatedServerRouteImport } from './routes/api/tmdb/movies.top-rated'
import { ServerRoute as ApiTmdbMoviesPopularServerRouteImport } from './routes/api/tmdb/movies.popular'
import { ServerRoute as ApiTmdbMoviesNowPlayingServerRouteImport } from './routes/api/tmdb/movies.now-playing'
import { ServerRoute as ApiTmdbMoviesIdServerRouteImport } from './routes/api/tmdb/movies.$id'
import { ServerRoute as ApiTmdbPeopleIdMoviesServerRouteImport } from './routes/api/tmdb/people.$id.movies'
import { ServerRoute as ApiTmdbMoviesIdCreditsServerRouteImport } from './routes/api/tmdb/movies.$id.credits'

const rootServerRouteImport = createServerRootRoute()

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const _adminAnalyticsRoute = _adminAnalyticsRouteImport.update({
  id: '/__admin/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const CustomScriptDotjsServerRoute = CustomScriptDotjsServerRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersUserIdServerRoute = ApiUsersUserIdServerRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersServerRoute,
} as any)
const ApiTmdbSearchServerRoute = ApiTmdbSearchServerRouteImport.update({
  id: '/api/tmdb/search',
  path: '/api/tmdb/search',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTmdbMultiSearchServerRoute =
  ApiTmdbMultiSearchServerRouteImport.update({
    id: '/api/tmdb/multi-search',
    path: '/api/tmdb/multi-search',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAnalyticsVisitServerRoute = ApiAnalyticsVisitServerRouteImport.update({
  id: '/api/analytics/visit',
  path: '/api/analytics/visit',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAnalyticsSummaryServerRoute =
  ApiAnalyticsSummaryServerRouteImport.update({
    id: '/api/analytics/summary',
    path: '/api/analytics/summary',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbPeopleSearchServerRoute =
  ApiTmdbPeopleSearchServerRouteImport.update({
    id: '/api/tmdb/people/search',
    path: '/api/tmdb/people/search',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesUpcomingServerRoute =
  ApiTmdbMoviesUpcomingServerRouteImport.update({
    id: '/api/tmdb/movies/upcoming',
    path: '/api/tmdb/movies/upcoming',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesTrendingServerRoute =
  ApiTmdbMoviesTrendingServerRouteImport.update({
    id: '/api/tmdb/movies/trending',
    path: '/api/tmdb/movies/trending',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesTopRatedServerRoute =
  ApiTmdbMoviesTopRatedServerRouteImport.update({
    id: '/api/tmdb/movies/top-rated',
    path: '/api/tmdb/movies/top-rated',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesPopularServerRoute =
  ApiTmdbMoviesPopularServerRouteImport.update({
    id: '/api/tmdb/movies/popular',
    path: '/api/tmdb/movies/popular',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesNowPlayingServerRoute =
  ApiTmdbMoviesNowPlayingServerRouteImport.update({
    id: '/api/tmdb/movies/now-playing',
    path: '/api/tmdb/movies/now-playing',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesIdServerRoute = ApiTmdbMoviesIdServerRouteImport.update({
  id: '/api/tmdb/movies/$id',
  path: '/api/tmdb/movies/$id',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTmdbPeopleIdMoviesServerRoute =
  ApiTmdbPeopleIdMoviesServerRouteImport.update({
    id: '/api/tmdb/people/$id/movies',
    path: '/api/tmdb/people/$id/movies',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTmdbMoviesIdCreditsServerRoute =
  ApiTmdbMoviesIdCreditsServerRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => ApiTmdbMoviesIdServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/movies': typeof MoviesRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/search': typeof SearchRoute
  '/users': typeof UsersRouteWithChildren
  '/analytics': typeof _adminAnalyticsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/movies': typeof MoviesRoute
  '/redirect': typeof RedirectRoute
  '/search': typeof SearchRoute
  '/analytics': typeof _adminAnalyticsRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/movies': typeof MoviesRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/search': typeof SearchRoute
  '/users': typeof UsersRouteWithChildren
  '/__admin/analytics': typeof _adminAnalyticsRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/movies'
    | '/posts'
    | '/redirect'
    | '/search'
    | '/users'
    | '/analytics'
    | '/movie/$movieId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/movies'
    | '/redirect'
    | '/search'
    | '/analytics'
    | '/movie/$movieId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/deferred'
    | '/movies'
    | '/posts'
    | '/redirect'
    | '/search'
    | '/users'
    | '/__admin/analytics'
    | '/_pathlessLayout/_nested-layout'
    | '/movie/$movieId'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  MoviesRoute: typeof MoviesRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  SearchRoute: typeof SearchRoute
  UsersRoute: typeof UsersRouteWithChildren
  _adminAnalyticsRoute: typeof _adminAnalyticsRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}
export interface FileServerRoutesByFullPath {
  '/customScript.js': typeof CustomScriptDotjsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/analytics/summary': typeof ApiAnalyticsSummaryServerRoute
  '/api/analytics/visit': typeof ApiAnalyticsVisitServerRoute
  '/api/tmdb/multi-search': typeof ApiTmdbMultiSearchServerRoute
  '/api/tmdb/search': typeof ApiTmdbSearchServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/tmdb/movies/$id': typeof ApiTmdbMoviesIdServerRouteWithChildren
  '/api/tmdb/movies/now-playing': typeof ApiTmdbMoviesNowPlayingServerRoute
  '/api/tmdb/movies/popular': typeof ApiTmdbMoviesPopularServerRoute
  '/api/tmdb/movies/top-rated': typeof ApiTmdbMoviesTopRatedServerRoute
  '/api/tmdb/movies/trending': typeof ApiTmdbMoviesTrendingServerRoute
  '/api/tmdb/movies/upcoming': typeof ApiTmdbMoviesUpcomingServerRoute
  '/api/tmdb/people/search': typeof ApiTmdbPeopleSearchServerRoute
  '/api/tmdb/movies/$id/credits': typeof ApiTmdbMoviesIdCreditsServerRoute
  '/api/tmdb/people/$id/movies': typeof ApiTmdbPeopleIdMoviesServerRoute
}
export interface FileServerRoutesByTo {
  '/customScript.js': typeof CustomScriptDotjsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/analytics/summary': typeof ApiAnalyticsSummaryServerRoute
  '/api/analytics/visit': typeof ApiAnalyticsVisitServerRoute
  '/api/tmdb/multi-search': typeof ApiTmdbMultiSearchServerRoute
  '/api/tmdb/search': typeof ApiTmdbSearchServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/tmdb/movies/$id': typeof ApiTmdbMoviesIdServerRouteWithChildren
  '/api/tmdb/movies/now-playing': typeof ApiTmdbMoviesNowPlayingServerRoute
  '/api/tmdb/movies/popular': typeof ApiTmdbMoviesPopularServerRoute
  '/api/tmdb/movies/top-rated': typeof ApiTmdbMoviesTopRatedServerRoute
  '/api/tmdb/movies/trending': typeof ApiTmdbMoviesTrendingServerRoute
  '/api/tmdb/movies/upcoming': typeof ApiTmdbMoviesUpcomingServerRoute
  '/api/tmdb/people/search': typeof ApiTmdbPeopleSearchServerRoute
  '/api/tmdb/movies/$id/credits': typeof ApiTmdbMoviesIdCreditsServerRoute
  '/api/tmdb/people/$id/movies': typeof ApiTmdbPeopleIdMoviesServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/customScript.js': typeof CustomScriptDotjsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/analytics/summary': typeof ApiAnalyticsSummaryServerRoute
  '/api/analytics/visit': typeof ApiAnalyticsVisitServerRoute
  '/api/tmdb/multi-search': typeof ApiTmdbMultiSearchServerRoute
  '/api/tmdb/search': typeof ApiTmdbSearchServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/tmdb/movies/$id': typeof ApiTmdbMoviesIdServerRouteWithChildren
  '/api/tmdb/movies/now-playing': typeof ApiTmdbMoviesNowPlayingServerRoute
  '/api/tmdb/movies/popular': typeof ApiTmdbMoviesPopularServerRoute
  '/api/tmdb/movies/top-rated': typeof ApiTmdbMoviesTopRatedServerRoute
  '/api/tmdb/movies/trending': typeof ApiTmdbMoviesTrendingServerRoute
  '/api/tmdb/movies/upcoming': typeof ApiTmdbMoviesUpcomingServerRoute
  '/api/tmdb/people/search': typeof ApiTmdbPeopleSearchServerRoute
  '/api/tmdb/movies/$id/credits': typeof ApiTmdbMoviesIdCreditsServerRoute
  '/api/tmdb/people/$id/movies': typeof ApiTmdbPeopleIdMoviesServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/customScript.js'
    | '/api/users'
    | '/api/analytics/summary'
    | '/api/analytics/visit'
    | '/api/tmdb/multi-search'
    | '/api/tmdb/search'
    | '/api/users/$userId'
    | '/api/tmdb/movies/$id'
    | '/api/tmdb/movies/now-playing'
    | '/api/tmdb/movies/popular'
    | '/api/tmdb/movies/top-rated'
    | '/api/tmdb/movies/trending'
    | '/api/tmdb/movies/upcoming'
    | '/api/tmdb/people/search'
    | '/api/tmdb/movies/$id/credits'
    | '/api/tmdb/people/$id/movies'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/customScript.js'
    | '/api/users'
    | '/api/analytics/summary'
    | '/api/analytics/visit'
    | '/api/tmdb/multi-search'
    | '/api/tmdb/search'
    | '/api/users/$userId'
    | '/api/tmdb/movies/$id'
    | '/api/tmdb/movies/now-playing'
    | '/api/tmdb/movies/popular'
    | '/api/tmdb/movies/top-rated'
    | '/api/tmdb/movies/trending'
    | '/api/tmdb/movies/upcoming'
    | '/api/tmdb/people/search'
    | '/api/tmdb/movies/$id/credits'
    | '/api/tmdb/people/$id/movies'
  id:
    | '__root__'
    | '/customScript.js'
    | '/api/users'
    | '/api/analytics/summary'
    | '/api/analytics/visit'
    | '/api/tmdb/multi-search'
    | '/api/tmdb/search'
    | '/api/users/$userId'
    | '/api/tmdb/movies/$id'
    | '/api/tmdb/movies/now-playing'
    | '/api/tmdb/movies/popular'
    | '/api/tmdb/movies/top-rated'
    | '/api/tmdb/movies/trending'
    | '/api/tmdb/movies/upcoming'
    | '/api/tmdb/people/search'
    | '/api/tmdb/movies/$id/credits'
    | '/api/tmdb/people/$id/movies'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  CustomScriptDotjsServerRoute: typeof CustomScriptDotjsServerRoute
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
  ApiAnalyticsSummaryServerRoute: typeof ApiAnalyticsSummaryServerRoute
  ApiAnalyticsVisitServerRoute: typeof ApiAnalyticsVisitServerRoute
  ApiTmdbMultiSearchServerRoute: typeof ApiTmdbMultiSearchServerRoute
  ApiTmdbSearchServerRoute: typeof ApiTmdbSearchServerRoute
  ApiTmdbMoviesIdServerRoute: typeof ApiTmdbMoviesIdServerRouteWithChildren
  ApiTmdbMoviesNowPlayingServerRoute: typeof ApiTmdbMoviesNowPlayingServerRoute
  ApiTmdbMoviesPopularServerRoute: typeof ApiTmdbMoviesPopularServerRoute
  ApiTmdbMoviesTopRatedServerRoute: typeof ApiTmdbMoviesTopRatedServerRoute
  ApiTmdbMoviesTrendingServerRoute: typeof ApiTmdbMoviesTrendingServerRoute
  ApiTmdbMoviesUpcomingServerRoute: typeof ApiTmdbMoviesUpcomingServerRoute
  ApiTmdbPeopleSearchServerRoute: typeof ApiTmdbPeopleSearchServerRoute
  ApiTmdbPeopleIdMoviesServerRoute: typeof ApiTmdbPeopleIdMoviesServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/__admin/analytics': {
      id: '/__admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof _adminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
    '/api/tmdb/search': {
      id: '/api/tmdb/search'
      path: '/api/tmdb/search'
      fullPath: '/api/tmdb/search'
      preLoaderRoute: typeof ApiTmdbSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/multi-search': {
      id: '/api/tmdb/multi-search'
      path: '/api/tmdb/multi-search'
      fullPath: '/api/tmdb/multi-search'
      preLoaderRoute: typeof ApiTmdbMultiSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/analytics/visit': {
      id: '/api/analytics/visit'
      path: '/api/analytics/visit'
      fullPath: '/api/analytics/visit'
      preLoaderRoute: typeof ApiAnalyticsVisitServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/analytics/summary': {
      id: '/api/analytics/summary'
      path: '/api/analytics/summary'
      fullPath: '/api/analytics/summary'
      preLoaderRoute: typeof ApiAnalyticsSummaryServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/people/search': {
      id: '/api/tmdb/people/search'
      path: '/api/tmdb/people/search'
      fullPath: '/api/tmdb/people/search'
      preLoaderRoute: typeof ApiTmdbPeopleSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/upcoming': {
      id: '/api/tmdb/movies/upcoming'
      path: '/api/tmdb/movies/upcoming'
      fullPath: '/api/tmdb/movies/upcoming'
      preLoaderRoute: typeof ApiTmdbMoviesUpcomingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/trending': {
      id: '/api/tmdb/movies/trending'
      path: '/api/tmdb/movies/trending'
      fullPath: '/api/tmdb/movies/trending'
      preLoaderRoute: typeof ApiTmdbMoviesTrendingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/top-rated': {
      id: '/api/tmdb/movies/top-rated'
      path: '/api/tmdb/movies/top-rated'
      fullPath: '/api/tmdb/movies/top-rated'
      preLoaderRoute: typeof ApiTmdbMoviesTopRatedServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/popular': {
      id: '/api/tmdb/movies/popular'
      path: '/api/tmdb/movies/popular'
      fullPath: '/api/tmdb/movies/popular'
      preLoaderRoute: typeof ApiTmdbMoviesPopularServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/now-playing': {
      id: '/api/tmdb/movies/now-playing'
      path: '/api/tmdb/movies/now-playing'
      fullPath: '/api/tmdb/movies/now-playing'
      preLoaderRoute: typeof ApiTmdbMoviesNowPlayingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/$id': {
      id: '/api/tmdb/movies/$id'
      path: '/api/tmdb/movies/$id'
      fullPath: '/api/tmdb/movies/$id'
      preLoaderRoute: typeof ApiTmdbMoviesIdServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/people/$id/movies': {
      id: '/api/tmdb/people/$id/movies'
      path: '/api/tmdb/people/$id/movies'
      fullPath: '/api/tmdb/people/$id/movies'
      preLoaderRoute: typeof ApiTmdbPeopleIdMoviesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/tmdb/movies/$id/credits': {
      id: '/api/tmdb/movies/$id/credits'
      path: '/credits'
      fullPath: '/api/tmdb/movies/$id/credits'
      preLoaderRoute: typeof ApiTmdbMoviesIdCreditsServerRouteImport
      parentRoute: typeof ApiTmdbMoviesIdServerRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersServerRouteChildren {
  ApiUsersUserIdServerRoute: typeof ApiUsersUserIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersUserIdServerRoute: ApiUsersUserIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

interface ApiTmdbMoviesIdServerRouteChildren {
  ApiTmdbMoviesIdCreditsServerRoute: typeof ApiTmdbMoviesIdCreditsServerRoute
}

const ApiTmdbMoviesIdServerRouteChildren: ApiTmdbMoviesIdServerRouteChildren = {
  ApiTmdbMoviesIdCreditsServerRoute: ApiTmdbMoviesIdCreditsServerRoute,
}

const ApiTmdbMoviesIdServerRouteWithChildren =
  ApiTmdbMoviesIdServerRoute._addFileChildren(
    ApiTmdbMoviesIdServerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  MoviesRoute: MoviesRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  SearchRoute: SearchRoute,
  UsersRoute: UsersRouteWithChildren,
  _adminAnalyticsRoute: _adminAnalyticsRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  CustomScriptDotjsServerRoute: CustomScriptDotjsServerRoute,
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
  ApiAnalyticsSummaryServerRoute: ApiAnalyticsSummaryServerRoute,
  ApiAnalyticsVisitServerRoute: ApiAnalyticsVisitServerRoute,
  ApiTmdbMultiSearchServerRoute: ApiTmdbMultiSearchServerRoute,
  ApiTmdbSearchServerRoute: ApiTmdbSearchServerRoute,
  ApiTmdbMoviesIdServerRoute: ApiTmdbMoviesIdServerRouteWithChildren,
  ApiTmdbMoviesNowPlayingServerRoute: ApiTmdbMoviesNowPlayingServerRoute,
  ApiTmdbMoviesPopularServerRoute: ApiTmdbMoviesPopularServerRoute,
  ApiTmdbMoviesTopRatedServerRoute: ApiTmdbMoviesTopRatedServerRoute,
  ApiTmdbMoviesTrendingServerRoute: ApiTmdbMoviesTrendingServerRoute,
  ApiTmdbMoviesUpcomingServerRoute: ApiTmdbMoviesUpcomingServerRoute,
  ApiTmdbPeopleSearchServerRoute: ApiTmdbPeopleSearchServerRoute,
  ApiTmdbPeopleIdMoviesServerRoute: ApiTmdbPeopleIdMoviesServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
